config/routes.rb
Rails.application.routes.draw do
  # Sidekiq
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
  # Error pages
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#server_error', via: :all

  # TAG
  get 'tags/:tag', to: 'tasks#index', as: :tag

  # ADMIN
  namespace :admin, path: 'splatoon' do
    resources :tasks
    resources :users do
      member do
        get :task
      end
    end
    get 'sign_up', to: 'users#new'
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
  end
  # TASK
  resources :tasks do
    collection do
      get :user
    end
  end
  # SESSION
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # USER
  get 'sign_up', to: 'users#new'
  resources :users, except: [:new]
  # PAGE
  root 'pages#index'
end

app/views/shared/frontend/_flash.html.erb
<div class="alert alert-secondary" role="alert">
  <%= notice %>
</div>

app/views/shared/frontend/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark p-3">
  <%= link_to "Task Manager", root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to t('tasks.index_task'), tasks_path , class: 'nav-link' %>
      </li>
      <% if logged_in? && current_user.admin? %>
        <li class="nav-item">
          <%= link_to t('attributes.tasks.backend'), admin_users_path , class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
    <%= form_tag(tasks_path, method: 'get', class: 'd-flex') do %>
      <form class="form-inline my-2 my-lg-10">
        <%= search_form_for @q do |f| %>
          <%= f.input :tags_name_eq, ad: :select, label: false, collection: Tag.all, label_method: :name, value_method: :name, required: false, placeholder:"搜尋標籤" %>
          <%= f.search_field :title_or_content_cont, class:"form-control mr-sm-2", type:"search", placeholder:"搜尋標題或內容"%>
          <%= f.submit class:"btn btn-outline-light my-2 my-sm-0" %>
        <% end %>
      </form>
    <% end %>

    <ul class="navbar-nav">
        <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.username.upcase %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to t('.my_task'), user_tasks_path(current_user) , class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>          
            <%= link_to t('.new_task'), new_task_path , class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>
            <%= link_to t('.settings'), edit_user_path(current_user) , class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>
            <%= link_to t('.logout'), logout_path, method:'delete' , class: 'dropdown-item'%>
          </div>
        </li> 
        <% else %>
          <li class="nav-item">
            <%= link_to "登入", login_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "註冊", sign_up_path, class: 'nav-link' %>
          </li>
        <% end %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= t('.language') %>
          </a>
          <div class="dropdown-menu p-2" aria-labelledby="navbarDropdown">
            <%= link_to('中文', :locale => 'zh-TW', class: 'dropdown-item') %>
            <div class="dropdown-divider"></div> 
            <%= link_to('English', :locale => 'en', class: 'dropdown-item') %>
          </div>
        </li>       
    </ul>

  </<%=>
</nav>

app/views/shared/frontend/_navbar_admin.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary p-3">
  <%= link_to "Task Manager", root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to t('tasks.index_task'), admin_tasks_path , class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to t('tasks.index_user'), admin_users_path , class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "前台", user_tasks_path(current_user) , class: 'nav-link' %>
      </li>
    </ul>
    <%= form_tag(admin_tasks_path, method: 'get', class: 'd-flex') do %>
      <form class="form-inline my-2 my-lg-0">
        <%= search_form_for @q do |f| %>
          <%= f.search_field :title_or_content_cont, class:"form-control mr-sm-2", type:"search", placeholder:"搜尋標題或內容"%>
          <%= f.submit class:"btn btn-outline-light my-2 my-sm-0" %>
        <% end %>
      </form>
    <% end %>

    <ul class="navbar-nav">
        <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.username.upcase %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to t('attributes.tasks.my_task'), task_admin_user_path(current_user) , class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>          
            <%= link_to t('attributes.tasks.new_task'), new_admin_task_path , class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>
            <%= link_to t('attributes.tasks.setting'), edit_admin_user_path(current_user) , class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>
            <%= link_to t('attributes.tasks.logout'), admin_logout_path, method:'delete' , class: 'dropdown-item'%>
          </div>
        </li> 
        <% else %>
          <li class="nav-item">
            <%= link_to "登入", admin_login_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%#= link_to "註冊", admin_sign_up_path, class: 'nav-link' %>
          </li>
        <% end %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= t('attributes.tasks.language') %>
          </a>
          <div class="dropdown-menu p-2" aria-labelledby="navbarDropdown">
            <%= link_to('中文', :locale => 'zh-TW', class: 'dropdown-item') %>
            <div class="dropdown-divider"></div> 
            <%= link_to('English', :locale => 'en', class: 'dropdown-item') %>
          </div>
        </li>       
    </ul>

  </div>
</nav>