config/routes.rb
Rails.application.routes.draw do
  # Sidekiq
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
  # Error pages
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#server_error', via: :all

  # TAG
  get 'tags/:tag', to: 'tasks#index', as: :tag

  # ADMIN
  namespace :admin, path: 'splatoon' do
    resources :tasks
    resources :users do
      member do
        get :task
      end
    end
    get 'sign_up', to: 'users#new'
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
  end
  # TASK
  resources :tasks do
    collection do
      get :user
    end
  end
  # SESSION
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # USER
  get 'sign_up', to: 'users#new'
  resources :users, except: [:new]
  # PAGE
  root 'pages#index'
end

app/models/user.rb
class User < ApplicationRecord
  before_destroy :last_admin_check
  has_many :tasks, dependent: :destroy # 刪除使用者後，也會一併刪除該使用者的任務
  validates :username, presence: true
  validates :email, presence: true, uniqueness: true
  has_secure_password

  private

  # 如果admin剩最後一個 無法被刪除
  def last_admin_check
    if User.where(admin: true).count == 1 && self.admin
      errors.add(:base, '無法刪除唯一管理者')
      throw(:abort)
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  #  the order of before_action matters here
  before_action :find_user, only:[:edit,:show, :update, :destroy, :task]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, notice: "#{@user.username} 已註冊成功！"
    else
      @error_message = @user.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit; end

  def show; end

  def update
    if @user.update(user_params)
      redirect_to admin_users_path, notice: '更新帳戶成功'
    else
      @error_message = @user.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    if @user != current_user
      if @user.destroy
        redirect_to admin_users_path, notice: '刪除帳戶成功'
      else
        redirect_to admin_users_path, notice: @user.errors.full_messages.to_sentence
      end
    else
      if @user.destroy
        session[:user_id] = nil
        redirect_to admin_users_path, notice: '刪除帳戶成功'
      else
        redirect_to admin_users_path, notice: @user.errors.full_messages.to_sentence
      end
    end
  end

  # 取得使用者的所有任務
  def task
    @q = @user.tasks.ransack(params[:q])
    @tasks = @q.result(distinct: true).page params[:page]
  end

  private

  def find_user
    @user = User.find_by(id: params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :admin)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# rubocop:disable Style/AsciiComments
# Your comment
class UsersController < ApplicationController
  before_action :login_check, except: %i[new create]
  before_action :find_user, only: %i[edit show update destroy]
  before_action :same_user_check, only: %i[edit update destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      MailWorker.perform_async(@user.id)
      redirect_to root_path, notice: "#{@user.username} 已註冊成功！"
    else
      @error_message = @user.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit; end

  def show; end

  def update
    if @user.update(user_params)
      redirect_to user_tasks_path(current_user), notice: '更新帳戶成功'
    else
      @error_message = @user.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    redirect_to user_tasks_path(current_user), notice: '刪除帳戶成功' if @user.destroy
  end

  private

  def find_user
    @user = User.find_by(id: params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end
# rubocop:enable Style/AsciiComments

app/helpers/users_helper.rb
module UsersHelper
  def user_role(x)
    x ? t('attributes.users.admin') : t('attributes.users.member')
  end
end

app/views/admin/users/_form_user.html.erb
<h3> <%= error_message %> </h3>

<%= simple_form_for [:admin, user] do |form| %>
  <div class="wrap">
    <%= form.input :username, label: t("attributes.users.username") %> 
    <%= form.input :email, label: t("attributes.users.email") %>
    <%= form.input :password, label: t("attributes.users.password") %>
    <%= form.input :admin, label: t("attributes.users.register_admin") %>

    <%= form.submit%>
  </div>

<% end %>

app/views/admin/users/edit.html.erb
<h1>編輯使用者</h1>

<%= render 'form_user', user: @user, error_message: @error_message %>

app/views/admin/users/index.html.erb
<h1><%= t('attributes.tasks.backend') %>： <%=t('users.index_user') %></h1>

<table class="table table-hover">
  <thead>
    <tr>
      <td><%= t('attributes.users.username') %></td>
      <td><%= t('attributes.users.email') %></td>
      <td><%= t('attributes.users.role') %>
      <td><%= t('attributes.tasks.task_count') %></td>
      <td><%= t('attributes.users.action') %></td>
    </tr>
  </thead>
  
  <tbody>
    <% @users.each do |user| %>
      <tr>
      <td><%= link_to user.username, task_admin_user_path(user) %></td>
      <td><%= user.email %></td>
      <td><%= user_role(user.admin) %>
      <td><%= user.tasks.count %></td> <%# 顯示使用者的任務數量 %>
      <td>
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to t("users.edit"), edit_admin_user_path(user) , class: 'dropdown-item' %>
          <div class="dropdown-divider"></div>          
          <%= link_to t("users.show"), admin_user_path(user) , class: 'dropdown-item' %>
          <div class="dropdown-divider"></div>
          <%= link_to t("users.delete"), admin_user_path(user) , class: 'dropdown-item', method: 'delete', data: { confirm: "確認刪除嗎？"}%>
        </div>
      </td>
    </tr>
    <% end %>

  </tbody>
</table>

<%= button_to t("users.create"), admin_sign_up_path ,class:"btn btn-outline-dark", method: "get"%>

app/views/admin/users/new.html.erb
<h1>新增使用者</h1>

<%= render 'form_user', user: @user, error_message: @error_message %>

app/views/admin/users/show.html.erb
  <div class="card" style="width: 50rem;">
    <h1><div class="card-header"> <%= t("attributes.users.account_info") %></div></h1>

    <ul class="list-group list-group-flush">
      <li class="list-group-item"> <%= t("attributes.users.email") %>: <%= @user.email %> </li>
      <li class="list-group-item"> <%= t("attributes.users.username") %>: <%= @user.username %> </li>
    </ul>
  </div>

app/views/admin/users/task.html.erb
<h1><%=t("tasks.index_task")%></h1>

<%= paginate @tasks, theme: 'twitter-bootstrap-4' %>
<% if params[:q] %>
  <h4>搜尋結果共: <%= @tasks.count %> 筆 </h4>
<% end %>
<table class= "table table-hover">
  <thead>
    <tr>
      <th scope="col"><%= sort_link(@q, :id, t("tasks.task_id"), id: "title", default_order: :desc) %></th>
      <th scope="col"><%= t("tasks.task_title") %></th>
      <th scope="col"><%= t("tasks.task_owner") %></th>
      <th scope="col"><%= sort_link(@q, :priority, t("tasks.task_priority"), id: "priority", default_order: :desc) %></th>
      <th scope="col"><%= t("tasks.task_begin") %></th>
      <th scope="col"><%= sort_link(@q, :task_end, t("tasks.task_end"), id: "task_end", default_order: :asc) %></th>
      <th scope="col">
        <% if @q %>
          <%= search_form_for @q do |f| %>
            <%= f.input :status_eq, as: :select, collection:[[1, t('tasks.status_pending')], [2, t('tasks.status_proceeding')], [3, t('tasks.status_done')]], 
                label_method: :second, value_method: :first, label: false %>
            <%= f.submit class:"btn btn-outline-dark" , style: 'display: none;', id: "btn-status"%>
          <% end %>
        <% end %>
      </th>
      <th><%= t('attributes.users.action') %></th>
    </tr>
  </thead>
  
  
    <% @tasks.each do |task| %>
    <tr>
      <td><%= task.id %></td>
      <td><%= link_to task.title, task_path(task) %></td>
      <td><%= task.user.username %></td>
      <td><%= t("tasks.priority_#{task.priority}") %></td>
      <td><%= task.task_begin.to_s(:short) %></td>
      <td><%= task.task_end.to_s(:short) %></td>      
      <td><%= t("tasks.status_#{task.status}") %></td>
      <td>
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to t("tasks.edit"), edit_admin_task_path(task) , class: 'dropdown-item' %>
          <div class="dropdown-divider"></div>          
          <%= link_to t("tasks.show"), admin_task_path(task) , class: 'dropdown-item' %>
          <div class="dropdown-divider"></div>
          <%= link_to t("tasks.delete"), admin_task_path(task) , class: 'dropdown-item', method: 'delete', data: { confirm: "確認刪除嗎？"}%>
      </td> 
    </tr>
    <% end %>
  
</table>

<%= button_to t("tasks.create"), new_task_path ,class:"btn btn-outline-dark", method: "get"%>

<script>

$( document ).on('turbolinks:load', function() {
  console.log("hihihi")
  const status = document.getElementById('q_status_eq')

  status.addEventListener('change', () => {
    document.querySelector('#btn-status').click();
  });

});
</script>